# cargo-deny configuration for license compliance
# https://embarkstudios.github.io/cargo-deny/

[licenses]
# List of explicitly allowed licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception", 
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "0BSD",
    "Unlicense",
]

# List of explicitly disallowed licenses
deny = [
    "GPL-2.0",
    "GPL-3.0", 
    "AGPL-3.0",
    "LGPL-2.1",
    "LGPL-3.0",
    "EUPL-1.2",
    "OSL-3.0",
    "CDDL-1.0",
    "EPL-2.0",
    "MPL-2.0",
]

# Lint level for when multiple versions of the same license are detected
multiple-versions = "warn"

# Lint level for when a crate version requirement is neither part of
# a publicly published crate, nor is available in a git repository
unlicensed = "deny"

# Lint level for when an SPDX expression is detected that does not match
# the crate's license metadata
confidence-threshold = 0.8

# Some crates don't have (easily) machine readable licensing information,
# adding a clarification or license text here will always be taken into account
[[licenses.clarify]]
name = "ring"
# SPDX identifier for the license
license = "MIT AND ISC AND OpenSSL"
# Override the license for a crate when the metadata is incorrect
expression = "MIT AND ISC AND OpenSSL"

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is neither part of
# a publicly published crate, nor is available in a git repository  
wildcards = "allow"
# The graph highlighting used when creating dotgraphs for crates
# with multiple versions
highlight = "all"

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"
# Lint level for what to happen when a crate from a git repository that is not
# in the allow list is encountered  
unknown-git = "warn"
# List of allowed registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
# List of allowed Git repositories
allow-git = []

[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"
# The url(s) of the advisory databases to use
db-urls = ["https://github.com/rustsec/advisory-db"]
# The lint level for security vulnerabilities
vulnerability = "deny"
# The lint level for unmaintained crates
unmaintained = "warn"
# The lint level for crates that have been yanked from their source registry
yanked = "warn"
# The lint level for crates with security notices. Note that as of
# 2019-12-17 there are no security notice advisories in
# https://github.com/rustsec/advisory-db
notice = "warn"
# A list of advisory IDs to ignore. Note that ignored advisories will still
# output a note when they are encountered.
ignore = []